### ISSUE TITLE
Could you give me an example collection.json?

### ISSUE THREAD

**Issue by chunel44** [jordanwalsh23/postman-local-mock-server#22]
Every .json I put I get the same error
`{"result":"Error","message":"Could not find a matching response based on your request parameters."}`

**Comment by jordanwalsh23** [comment]
You can check the test/collections folder in the repo for a bunch of different examples.

I also just quickly generated this. It has a single endpoint `/api/bookings` and it will generate some random data in the response.

[Sample Collection.postman_collection.json](https://github.com/user-attachments/files/16092605/Sample.Collection.postman_collection.json)

Start it like this:

```sh
postman-local -c "Sample Collection.postman_collection.json" -p 5678
```

and hit the endpoint like this:

```sh
curl http://localhost:5678/api/bookings
```

<img width="660" alt="image" src="https://github.com/jordanwalsh23/postman-local-mock-server/assets/1388936/6cada144-5350-4dbd-a2cf-dbb2e73680cc">

**Comment by chunel44** [comment]
Thx, your project helped me a lot 🔥
